

#default integer value for tournament timer (in seconds)
tournament-timer: 3600

#Scoreboard enabled true/false
scoreboard-setting: false

#default weights for event frequency
event:
  frequency: 10
  posWeight: 0.2
  negWeight: 0.2
  neutralWeight: 0.6

# Mob spawn event settings
mob-events:
  wolf-pack:
    mob-count: 4
    max-spawn-radius: 15
    min-spawn-radius: 5