#Configurations for the EventHorizon plugin

#default integer value for tournament timer (in seconds)
tournament-timer: 3600

#Scoreboard enabled true/false
scoreboard-setting: true

#default weights for event frequency
event:
  frequency: 2
  posWeight: 2
  negWeight: 2
  neutralWeight: 6

#to disable events, comment out the event name
enabled-events:
- "WolfPack" #MobSpawn: negative
- "IceIsNice" #BlockModification: neutral