

#default integer value for tournament timer (in seconds)
tournament-timer: 3600

#Scoreboard enabled true/false
scoreboard-setting: false

#default weights for event frequency
event:
  frequency: 10
  posWeight: 0.33
  negWeight: 0.33
  neutralWeight: 0.33

#determines if an event is enabled or disabled
events:
  enabled:
    - "WolfPack" #MobSpawn: negative
  disabled:
    - "IceIsNice" #BlockModification: neutral