# Configurations for the EventHorizon plugin

# default integer value for tournament timer (in seconds)
tournament-timer: 3600

# default weights for event frequency
# values relative to each other and do not need to add up to any specific number
event:
  frequency: 120
  posWeight: 3
  negWeight: 3
  neutralWeight: 3

# to disable events, comment out the event name by putting "#" in front of it
enabled-events:
- "Fasting" #attribute: negative
- "GrowthSpurt" #attribute: neutral
- "HalfAHeart" #attribute: negative
- "HoneyIShrunkTheKids" #attribute: negative
- "ZeroGravity" #attribute: neutral
- "IceIsNice" #blockmodification: neutral
- "GoldRush" #blockmodification: positive
- "NetherInvasion" #blockmodification: negative
- "DeepDarkInvasion" #blockmodification: negative
- "BlockDropShuffle" #dropmodification: neutral
- "DoubleOrNothing" #dropmodification: negative
- "MobDropShuffle" #dropmodification: neutral
- "FoodComa" #effects: neutral
- "GottaGoFast" #effects: positive
- "Overmine" #effects: positive
- "SecondWind" #effects: positive
- "YoureTooSlow" #effects: negative
- "ButterFingers" #inventoryAdjustment: negative
- "FlightSchool" #inventoryAdjustment: positive
- "InventorySwap" #inventoryAdjustment: neutral
- "SpoiledFood" #inventoryAdjustment: negative
- "DropParty" #itemspawn: positive
- "Feast" #itemspawn: positive
- "OreDropParty" #itemspawn: positive
- "ChickenFlock" #mobspawn: positive
- "CowHerd" #mobspawn: positive
- "DropCreeper" #mobspawn: negative
- "EndRaid" #mobspawn: negative
- "NetherRaid" #mobspawn: negative
- "RandomMobSpawn" #mobspawn: neutral
- "WolfPack" #mobspawn: negative
- "ZombieHorde" #mobspawn: negative
- "ZombieInvasion" #mobspawn: negative


