#Configurations for the EventHorizon plugin

#default integer value for tournament timer (in seconds)
tournament-timer: 3600

#default weights for event frequency
#values relative to each other and do not need to add up to any specific number
event:
  frequency: 10
  posWeight: 0
  negWeight: 2
  neutralWeight: 0

#to disable events, comment out the event name
enabled-events:
- "WolfPack" #MobSpawn: negative
- "IceIsNice" #BlockModification: neutral