

#default integer value for tournament timer (in seconds)
tournament-timer: 3600

#Scoreboard enabled true/false
scoreboard-setting: true

#default weights for event frequency
event:
  frequency: 2
  posWeight: 2
  negWeight: 2
  neutralWeight: 6

#determines if an event is enabled or disabled
events:
  enabled:
    - "WolfPack" #MobSpawn: negative
  disabled:
    - "IceIsNice" #BlockModification: neutral