name: EventHorizon
version: '1.0-SNAPSHOT'
main: capstone.team1.eventHorizon.EventHorizon
api-version: '1.21'
depend: ["PlaceholderAPI"]
commands:
  starttournament:
    description: Start the tournament timer.
    usage: /starttournament
  stoptournament:
    description: Stop the tournament timer.
    usage: /stoptournament